# Generated by Django 4.2.1 on 2023-05-27 16:22

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='datasource',
            name='key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='assets.folder')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='assets.tag')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='folders', through='assets.TagAssignment', to='assets.tag'),
        ),
    ]
