# Generated by Django 4.2.1 on 2023-05-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_tag_alter_datasource_key_tagassignment_folder_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datarepository',
            options={'verbose_name_plural': 'Data Repositories'},
        ),
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='datarepository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='datarepository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='folders', through='assets.TagAssignment', to='assets.tag'),
        ),
    ]
