# Generated by Django 4.2.1 on 2023-05-23 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workspace_workspaceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspaceassignment',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceassignment',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceassignment',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceassignment',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
