# Generated by Django 4.2.1 on 2023-05-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_created_at_workspace_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.workspace'),
        ),
    ]
