# Generated by Django 4.2.1 on 2023-05-29 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_alter_datarepository_options_file_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(choices=[('Customer Metrics', 'Customer Metrics'), ('Subscription Metrics', 'Subscription Metrics'), ('Revenue Metrics', 'Revenue Metrics'), ('Churn Metrics', 'Churn Metrics')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('customers/total', 'customers/total'), ('customers/active', 'customers/active'), ('subscription/total', 'subscription/total'), ('subscription/active', 'subscription/active'), ('subscription/trial', 'subscription/trial'), ('subscription/canceled', 'subscription/canceled'), ('mrr', 'mrr'), ('revenue/total', 'revenue/total'), ('arpu', 'arpu'), ('arr', 'arr'), ('churn/user', 'churn/user'), ('churn/revenue', 'churn/revenue')], max_length=255)),
                ('time', models.CharField(max_length=4)),
                ('data', models.DecimalField(decimal_places=10, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='metrics.metriccollection')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='assets.datasource')),
            ],
        ),
    ]
